-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bottom
(
    id bigserial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    price money NOT NULL,
    CONSTRAINT bottom_pkey PRIMARY KEY (id),
    CONSTRAINT bottom_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL DEFAULT nextval('order_id_seq'::regclass),
    customer_id bigint NOT NULL,
    create_date timestamp without time zone NOT NULL,
    desired_date timestamp without time zone NOT NULL,
    finish_date timestamp without time zone,
    bot bigint NOT NULL,
    top bigint NOT NULL,
    quant bigint NOT NULL,
    CONSTRAINT order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment
(
    id bigserial NOT NULL,
    order_id bigint NOT NULL,
    received_date timestamp without time zone NOT NULL,
    amount money NOT NULL,
    CONSTRAINT payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.top
(
    id bigserial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    price money NOT NULL,
    CONSTRAINT top_pkey PRIMARY KEY (id),
    CONSTRAINT top_name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    pwd character varying COLLATE pg_catalog."default" NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL,
    credit money NOT NULL,
    CONSTRAINT customer_id PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
);

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_bottom_id_fkey FOREIGN KEY (bot)
    REFERENCES public.bottom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_top_id_fkey FOREIGN KEY (top)
    REFERENCES public.top (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payment
    ADD CONSTRAINT payment_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
